version: 2
jobs:
    install:
        working_directory: ~/project
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout
            - run: python3 -m virtualenv venv --python=python3
            - run: echo "source ./venv/bin/activate" > $BASH_ENV
            - restore_cache:
                key: deps-pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run: python -m pip install -r requirements.txt
            - save_cache:
                key: deps-pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "venv"
    lint:
        working_directory: ~/project
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout
            - run: echo "source ./venv/bin/activate" > $BASH_ENV
            - restore_cache:
                key: deps-pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run: invoke lint
    test:
        working_directory: ~/project
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout
            - run: echo "source ./venv/bin/activate" > $BASH_ENV
            - restore_cache:
                key: deps-pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run: invoke test

workflows:
    version: 2
    pipeline:
        jobs:
            - install
            - lint:
                requires:
                    - install
            - test:
                requires:
                    - install
        
